### ISSUE TITLE
jump-to nav needs spacing on mobile

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/rhd-frontend#375]
I created some mocks here for responsive sizes. The white box that surrounds the text is 32px tall (6px spacer above and below the text) and the width for all items is based on the longest string of text plus 16px (8px spacer left and right of text). They will turn white with blue text on hover.

![Screen Shot 2019-10-16 at 11 09 10 AM](https://user-images.githubusercontent.com/30870144/66932343-6f0aeb00-f005-11e9-948d-ba806020f630.png)
![Screen Shot 2019-10-16 at 11 09 03 AM](https://user-images.githubusercontent.com/30870144/66932347-716d4500-f005-11e9-8ff4-7a75681c4de1.png)

**Comment by mindreeper2420** [comment]
@gdoyle1 setting the padding to 6px above/below & 8px left/right would set the item height to 32px tall (due to the link item line height and font size). If you want the item to only be 32px tall, then I can set the padding to 3px for top/bottom and 6px for right/left.

Padding of 6px & 8px:
<img width="842" alt="Screen Shot 2019-10-22 at 4 41 57 PM" src="https://user-images.githubusercontent.com/4032718/67330780-e56a8a00-f4ea-11e9-876d-455665fed1fb.png">

Padding of 3px and 6px:
<img width="836" alt="Screen Shot 2019-10-22 at 4 41 34 PM" src="https://user-images.githubusercontent.com/4032718/67330769-e1d70300-f4ea-11e9-9557-4dfcb93f4b81.png">

**Comment by gdoyle1** [comment]
Let's go with that first one so padding of 6px and 8px @mindreeper2420
